import {Faction} from "@AthenaPlugins//athena-plugin-factions/shared/interfaces";

export const ExampleFactionData : Faction[] = [
    {
        _id: 'a',
        bank: 0,
        settings: {},
        canDisband: true,
        members: { },
        name: 'LSPD',
        type: 'state',
        vehicles: [],
        ranks: [        ],
        storages: [],
        tickActions: [],
        actions: {}
    },
    {
        _id: 'b',
        bank: 0,
        settings: {},
        canDisband: true,
        members: {},
        name: 'LSMD',
        type: 'state',
        vehicles: [],
        ranks: [ ],
        storages: [],
        tickActions: [],
        actions: {}
    },
    {
        _id: 'a',
        bank: 0,
        settings: {},
        canDisband: true,
        members: { },
        name: 'LSPD',
        type: 'state',
        vehicles: [],
        ranks: [        ],
        storages: [],
        tickActions: [],
        actions: {}
    },
    {
        _id: 'b',
        bank: 0,
        settings: {},
        canDisband: true,
        members: {},
        name: 'LSMD',
        type: 'state',
        vehicles: [],
        ranks: [ ],
        storages: [],
        tickActions: [],
        actions: {}
    },
    {
        _id: 'a',
        bank: 0,
        settings: {},
        canDisband: true,
        members: { },
        name: 'LSPD',
        type: 'state',
        vehicles: [],
        ranks: [        ],
        storages: [],
        tickActions: [],
        actions: {}
    },
    {
        _id: 'b',
        bank: 0,
        settings: {},
        canDisband: true,
        members: {},
        name: 'LSMD',
        type: 'state',
        vehicles: [],
        ranks: [ ],
        storages: [],
        tickActions: [],
        actions: {}
    },
    {
        _id: 'a',
        bank: 0,
        settings: {},
        canDisband: true,
        members: { },
        name: 'LSPD',
        type: 'state',
        vehicles: [],
        ranks: [        ],
        storages: [],
        tickActions: [],
        actions: {}
    },
    {
        _id: 'b',
        bank: 0,
        settings: {},
        canDisband: true,
        members: {},
        name: 'LSMD',
        type: 'state',
        vehicles: [],
        ranks: [ ],
        storages: [],
        tickActions: [],
        actions: {}
    },
    {
        _id: 'a',
        bank: 0,
        settings: {},
        canDisband: true,
        members: { },
        name: 'LSPD',
        type: 'state',
        vehicles: [],
        ranks: [        ],
        storages: [],
        tickActions: [],
        actions: {}
    },
    {
        _id: 'b',
        bank: 0,
        settings: {},
        canDisband: true,
        members: {},
        name: 'LSMD',
        type: 'state',
        vehicles: [],
        ranks: [ ],
        storages: [],
        tickActions: [],
        actions: {}
    },
    {
        _id: 'a',
        bank: 0,
        settings: {},
        canDisband: true,
        members: { },
        name: 'LSPD',
        type: 'state',
        vehicles: [],
        ranks: [        ],
        storages: [],
        tickActions: [],
        actions: {}
    },
    {
        _id: 'b',
        bank: 0,
        settings: {},
        canDisband: true,
        members: {},
        name: 'LSMD',
        type: 'state',
        vehicles: [],
        ranks: [ ],
        storages: [],
        tickActions: [],
        actions: {}
    }
]